"""
===============================================================================
A-EYE TRACKER — End-to-End Application & Cloud Pipeline Debugging Harness
===============================================================================
Purpose:
This script serves as a standalone integration and debugging harness designed to
validate the entire downstream software and cloud automation workflow prior to
physical hardware deployment.

Key Responsibilities & Workflow Verification:
1. Sighting Simulation: Mocks inference outputs generated by the on-device TinyML
   model (e.g., target bird species, timestamps, quantity, GPS coordinates).
2. Database Ingestion: Tests schema compatibility, secure network handshakes, and
   data insertion into the Supabase PostgreSQL backend ('urban_observations').
3. Telemetry & Analytics Validation: Ensures data flows correctly into connected
   Grafana dashboards for real-time monitoring and visual analysis.
4. Automated Alert Dispatch: Verifies that real-time notification triggers parse
   field reports accurately and dispatch formatted Markdown messages to the
   dedicated Telegram channel via the Telegram Bot API.
===============================================================================
"""

import os
import requests
from datetime import datetime
from supabase import create_client, Client

# ==========================================
# 1. System Configurations
# ==========================================
SUPABASE_URL = "https://pxkevqlcaiazhgqrxbsp.supabase.co"
SUPABASE_KEY = "sb_publishable_igo1VwAo9FEGetZssdbFZQ_gOBRLIi3"

# Telegram Bot API credentials for automated incident alerting
TELEGRAM_BOT_TOKEN = "8809302299:AAGbuJe1Q9uifxL7ha7zHiQfZ6DYCs90W1k"
TELEGRAM_CHAT_ID = "-1003921648414"

print("🔄 Connecting to Supabase...")
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)


# ==========================================
# 2. Telegram Alert Dispatcher
# ==========================================
def send_telegram_alert(observations):
    """
    Sends a structured, real-time field report to the Telegram group,
    formatting all metadata fields from freshly synchronized sightings.
    """
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN.strip()}/sendMessage"
    total_records = len(observations)
    
    # Header Section
    message_lines = [
        "🚨 *A-EYE Tracker - Real-Time Field Report* 🚨",
        f"Synchronized *{total_records}* new detection(s) to the database.\n",
        "--- *Detailed Sighting Logs* ---"
    ]
    
    # Format sighting details dynamically
    for idx, obs in enumerate(observations, 1):
        bird_name = obs.get("bird_name", "Unknown Species")
        location = obs.get("location", "Unknown Location")
        observed_at = obs.get("observed_at", "N/A")
        quantity = obs.get("quantity", 1)
        lat = obs.get("latitude", "N/A")
        lon = obs.get("longitude", "N/A")
        
        item_block = (
            f"🦉 *Sighting #{idx}: {bird_name}*\n"
            f"  • *Count:* {quantity} unit(s)\n"
            f"  • *Timestamp:* {observed_at}\n"
            f"  • *Location Name:* {location}\n"
            f"  • *Coordinates:* `{lat}, {lon}`"
        )
        message_lines.append(item_block)
        
    # Footer Section
    message_lines.append("\n📊 _All records successfully compiled and updated in Supabase._")
    
    message_text = "\n".join(message_lines)

    payload = {
        "chat_id": TELEGRAM_CHAT_ID,
        "text": message_text,
        "parse_mode": "Markdown"
    }

    try:
        response = requests.post(url, json=payload, timeout=10)
        if response.status_code == 200:
            print("🚀 Detailed Telegram report sent successfully to the group!")
        else:
            print(f"❌ Failed to send Telegram alert. Status: {response.status_code}, Response: {response.text}")
    except Exception as e:
        print(f"⚠️ Error connecting to Telegram API: {e}")


# ==========================================
# 3. Main Debugging & Simulation Flow
# ==========================================
def main():
    """
    Simulates edge inference outputs, inserts records into Supabase,
    and triggers downstream alerting to validate the full automation chain.
    """
    # Simulated observation payload matching the on-device TinyML output schema
    observations_to_sync = [
        {
            "bird_name": "House Sparrow",
            "location": "Jerusalem Botanical Gardens, Givat Ram",
            "observed_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "quantity": 1,
            "latitude": 31.7683,
            "longitude": 35.2137
        }
    ]

    print(f"⏳ Starting synchronization of {len(observations_to_sync)} observations to Supabase...")
    successful_inserts = []

    for obs in observations_to_sync:
        try:
            response = supabase.table("urban_observations").insert(obs).execute()
            if response.data:
                successful_inserts.append(obs)
                print(f"  ✅ Successfully inserted: {obs['bird_name']} at {obs['location']}")
        except Exception as e:
            print(f"  ❌ Failed to insert record into Supabase: {e}")

    print(f"\n📊 Sync finished. Total records successfully saved in DB: {len(successful_inserts)}/{len(observations_to_sync)}")

    # ==========================================
    # 4. Trigger Downstream Telegram Notification
    # ==========================================
    if len(successful_inserts) > 0:
        print("🔔 Triggering advanced Telegram notification...")
        send_telegram_alert(successful_inserts)
    else:
        print("⏭️ No new rows were inserted. Skipping Telegram alert.")


if __name__ == "__main__":
    main()
